codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...90"

  status:
    project:
      default:
        target: 75%
        threshold: 10
        base: auto
    patch:
      default:
          enabled: no
          if_not_found: success
    changes:
      default:
        enabled: no
        if_not_found: success

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "header, diff"
  behavior: default
  require_changes: no